plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-since.cjs
    spec: 'https://raw.githubusercontent.com/toss/yarn-plugin-workspace-since/main/bundles/%40yarnpkg/plugin-workspace-since.js'

logFilters:
  - level: discard
    pattern: provides react * with version 18
  - level: discard
    pattern: provides react-dom * with version 18
  - level: discard
    pattern: provides @types/react * with version 18
  - level: discard
    pattern: '@types/jest * with version 29.1.2'

packageExtensions:
  '@docusaurus/theme-search-algolia@*':
    dependencies:
      '@algolia/client-search': ^4.9.1
      prism-react-renderer: ^1.2.1
  '@docsearch/react@*':
    peerDependencies:
      '@algolia/client-search': ^4.9.1
  '@svgr/core@*':
    peerDependencies:
      '@babel/core': '*'
  '@octokit/rest@^16':
    dependencies:
      '@octokit/core': ^3.0.0

supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux
